---
- name: remove test db
  mysql_db:
    name: test
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    state: absent
- name: remove anonymous accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
